"""Signal 1: LLM-based semantic assessment via Groq."""

import json
import os
import re

from groq import Groq

AI_PHRASES = (
    "it is important to note",
    "in today's world",
    "paradigm shift",
    "it is equally essential",
    "furthermore",
    "stakeholders",
    "delve",
    "comprehensive",
    "multifaceted",
    "leverage",
    "robust",
    "in conclusion",
    "on the other hand",
    "plays a crucial role",
)

HUMAN_MARKERS = (
    "honestly",
    "lol",
    "idk",
    "tbh",
    "ngl",
    "like ",
    "kinda",
    "gonna",
    "wanna",
    "?!",
    "...",
)


def _fallback_llm_score(text: str) -> float:
    """Heuristic fallback when Groq API is unavailable."""
    lower = text.lower()
    ai_hits = sum(1 for p in AI_PHRASES if p in lower)
    human_hits = sum(1 for m in HUMAN_MARKERS if m in lower)
    base = 0.45 + ai_hits * 0.08 - human_hits * 0.06
    if len(text.split()) < 30:
        base = base * 0.7 + 0.5 * 0.3
    return round(max(0.0, min(1.0, base)), 2)


def analyze_llm(text: str) -> float:
    """
    Return probability (0–1) that text is AI-generated.
    Uses Groq when GROQ_API_KEY is set; falls back to heuristics otherwise.
    """
    api_key = os.getenv("GROQ_API_KEY")
    if not api_key:
        return _fallback_llm_score(text)

    client = Groq(api_key=api_key)
    prompt = f"""Analyze the following text and assess whether it was likely written by a human or generated by AI.

Consider: formulaic transitions, hedging language, uniform structure, generic phrasing, lack of personal voice.

Respond with ONLY valid JSON in this exact format:
{{"ai_probability": 0.0}}

Where ai_probability is a float from 0.0 (definitely human) to 1.0 (definitely AI).

Text:
\"\"\"
{text[:3000]}
\"\"\""""

    try:
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[{"role": "user", "content": prompt}],
            temperature=0.1,
            max_tokens=50,
        )
        content = response.choices[0].message.content.strip()
        match = re.search(r"\{[^}]+\}", content)
        if match:
            data = json.loads(match.group())
            score = float(data.get("ai_probability", 0.5))
            return round(max(0.0, min(1.0, score)), 2)
    except Exception:
        pass

    return _fallback_llm_score(text)
